---
- name: Add group {{ user }}
  group:
    name: "{{ vault_user }}"
    gid: "{{ vault_user_id }}"
    state: present


- name: Add user {{ user }}
  user:
    name: "{{ vault_user }}"
    uid: "{{ vault_user_id }}"
    group: "{{ vault_user }}"
    password: "{{ ansibleVault.json.data.value }}"
    home: "/apps/{{ vault_user }}"
    shell: /bin/bash
    skeleton: /etc/skel
    create_home: yes
  tags: [ 'vault_user', 'vault_installdir' ]
...
