---
# - name: Add group {{ user }}
#   group:
#     name: "{{ vault_user }}"
#     gid: "{{ vault_user_id }}"
#     state: present
#
#
# - name: Add user {{ user }}
#   user:
#     name: "{{ vault_user }}"
#     uid: "{{ vault_user_id }}"
#     group: "{{ vault_user }}"
#     password: "{{ ansibleAuthPasswd.json.data.value }}"
#     home: "/apps/{{ vault_user }}"
#     shell: /bin/bash
#     skeleton: /etc/skel
#     create_home: yes
#   tags: [ 'vault_user', 'vault_installdir' ]

- name: create manifest Directory
  file:
    dest: "{{ item.dst }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  with_items:
    - { dst: '/usr/local/bin/manifests', mode: '0755', state: directory }
    - { dst: "{{ AppConfigs.json.data.syslog_volume }}", mode: '0755', state: directory }

- name: Render appConfig template
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'splunk_universal_forwarder.j2', dest: '/usr/local/bin/manifests/splunk_universal_forwarder.yml', owner: 'root', group: 'root', mode: '0660' }
  # when: ansible_hostname is search('usctvletcd0(1|2|3)v')

- name: Deploy splunk universal forwarder
  shell: docker-compose -f /usr/local/bin/manifests/splunk_universal_forwarder.yml up -d
  ignore_errors: true
  args:
    warn: false
    chdir: "/usr/local/bin/manifests"
  delay: 10
...
