---
- name: Install common packages with yum
  yum:
    name:
      - bc
      - sysstat
      - iptraf
      - rng-tools
      - yum-utils
      - epel-release
      - logrotate
    state: present

- name: Discover if [/etc/yum.repos.d/docker-ce.repo] exists
  stat:
    path: /etc/yum.repos.d/docker-ce.repo
  register: docker_ce_repo

- name: Add Docker repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  ignore_errors: true
  args:
    warn: false
  register: add_docker_repo
  when: not docker_ce_repo.stat.exists

- name: Discover if [/etc/yum.repos.d/rsyslog.repo] exists
  stat:
    path: /etc/yum.repos.d/rsyslog.repo
  register: rsyslog_repo

- name: Add Rsyslog repo
  shell: yum-config-manager --add-repo http://rpms.adiscon.com/v8-stable/rsyslog.repo
  ignore_errors: true
  args:
    warn: false
  register: add_docker_repo
  when: not rsyslog_repo.stat.exists

- name: Install docker-ce and supporting utils
  yum:
    name:
      - "docker-compose-{{docker.compose}}"
      - "docker-ce-{{docker.version}}"
      - "docker-ce-cli-{{docker.version}}"
    enablerepo: docker-ce-stable
    state: present

- name: service | {{ item }}
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - [ 'docker' ]
  tags: dockerService

# Set host in permissive mode
# Put SELinux in permissive mode, logging actions that would be blocked.
- selinux:
    policy: targeted
    state: permissive

# Run Compose to deploy container

# Put handler in docker restart
  notify:
    service docker restart
