---
# ansible-vault encrypt_string `openssl passwd -1 MarcusGarvey
#
# - name: Get Root Token
#   shell: cat /etc/vault/initfile | jq -r '.root_token'
#   ignore_errors: true
#   args:
#     warn: false
#   register: unSealToken

- name: Get User Vault Password
  uri:
    url: "{{ vaultUrl }}"
    method: GET
    headers:
      Content-Type: "application/json"
      X-Vault-Token: 's.9DPe4sj5NW26QcCtxeLL6auP'
      #X-Vault-Token: '{{unSealToken.stdout}}'
    status_code: 200
    force_basic_auth: yes
  register: ansibleVault

- debug:
    msg: "{{ ansibleVault.json.data.value }}"

- name: Write Vault Values to file
  lineinfile:
    create: yes
    dest: /tmp/.vaultUserpass
    state: present
    line: "{{ ansibleVault.json.data.value }}"



...
