---
- name: Write nexus Secrets to Vault
  uri:
    url: "{{ vaultUrl }}:{{ vaultUrlPort }}/v1/kv/ansible/nexus"
    method: POST
    body: {"password": "ansible-svc"}
    body_format: json
    status_code: 200
    force_basic_auth: yes
    return_content: yes
  register: ansibleAuthToken

- name: Get User Vault Password
   uri:
     url: "{{ vaultUrl }}:{{ vaultUrlPort }}/v1/kv/ansible/ansible-tC-pass"
     method: POST
     headers:
       Content-Type: "application/json"
       X-Vault-Token: '{{ ansibleAuthToken.json.auth.client_token }}'
     status_code: 200
     force_basic_auth: yes
   register: ansibleAuthPasswd
