---

- name: template Cluster Config| {{ item }}
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - { src: 'etcd.conf.j2', dest: '/etc/etcd/etcd.conf' }
  when: ansible_hostname is search('utrutstetcd0(1|2|3)v')

- name: Create ssh directory
  file:
    dest: "{{ item }}"
    mode: 0755
    state: directory
    owner: etcd
    group: etcd
  with_items:
    - /apps/etcd
    - /apps/etcd/vault-etcd.io

# - import_tasks: generate-cfssL-certs.yml

- name: Copy kitchenCI etcd cfsslCerts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'cfsslCerts/', dest: '{{ cert_dir }}', owner: 'root', group: 'etcd', mode: '0660' }
  when: ansible_hostname is search('utrutstetcd0(1|2|3)v')

- name: service | {{ item }}
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - [ 'etcd' ]
  tags: etcdService

- name: Wait for etcdService startup
  wait_for:
    timeout: 30
  delegate_to: localhost

  notify:
    - service etcd restart
