---
- firewalld: test-kitchen port | {{ item }}
    port={{ item }}
    immediate=yes
    permanent=true
    state=enabled
    zone=public
  with_items:
    - "2379/tcp"
    - "2380/tcp"
  tags: firewalld
  when: ansible_fqdn is search('utrutstetcd')

- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.fqdn }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items:
  - { ip: 10.13.3.15, fqdn: utrutstetcd01v.curbstone.com, name: utrutstetcd01v  }
  - { ip: 10.13.3.16, fqdn: utrutstetcd02v.curbstone.com, name: utrutstetcd02v  }
  - { ip: 10.13.3.17, fqdn: utrutstetcd03v.curbstone.com, name: utrutstetcd03v  }
  when: ansible_fqdn is search('utrutstetcd')

  notify:
    - service firewalld restart
