---
- import_tasks: configure-kitchenCI-named.yml
  tags: [configNamed]

- import_tasks: firewalld.yml
- import_tasks: dns_resolv_conf.yml
- import_tasks: common_pkgs.yml

- import_tasks: configure_etcd.yml
