---
- name: Import dns-server role
  import_role:
    name: dns-server

- import_tasks: firewalld.yml
- import_tasks: dns_resolv_conf.yml
- import_tasks: common_pkgs.yml

- import_tasks: configure_etcd.yml
