---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  connection: ssh
  remote_user: root

  # vars:
  #   mount_dir: "/opt/teamcity"
  #   user: "teamcity"
  #   user_id: "1202"

  roles:
    - vault-server
