---
- firewalld: test-kitchen port | {{ item }}
    port={{ item }}
    immediate=yes
    permanent=true
    state=enabled
    zone=public
  with_items:
    - "8200/tcp"
  tags: firewalld
  # when: ansible_fqdn is search('utrutsttcs01v')

- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.fqdn }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items:
  - { ip: 10.13.3.10, fqdn: utrutstvault01v.ssi.com, name: utrutstvault01v  }
  - { ip: 10.13.3.10, fqdn: utrutstvault02v.ssi.com, name: utrutstvault02v  }
  when: ansible_fqdn is search('utrutstvault01v')

  notify:
    - service restart firewalld
