---
- firewalld: test-kitchen port | {{ item }}
    port={{ item }}
    immediate=yes
    permanent=true
    state=enabled
    zone=public
  with_items:
    - "8200/tcp"
  tags: firewalld
  when: ansible_fqdn is search('usctvltstvlt01v')

- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.fqdn }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items:
  - { ip: 10.13.3.10, fqdn: usctvltstvlt01v.curbstoneops.com, name: usctvltstvlt01v  }
  - { ip: 10.13.3.11, fqdn: usctvltstvlt02v.curbstoneops.com, name: usctvltstvlt02v  }
  when: ansible_fqdn is search('usctvltstvlt01v')

  notify:
    - service restart firewalld
