---
  #
  # file: roles/vault/tasks/requirements.yml
  #
- name: Install common packages with yum
  yum:
    name:
      - bc
      - sysstat
      - iptraf
      - yum-utils
      - epel-release
      - logrotate
      - unzip
    state: present

- name: Install Vault Server Dependencies
  yum:
    name:
      - perl-libwww-perl
      - jq
    state: present
