---
- name: Add group {{ user }}
  group:
    name: "{{ vault_user }}"
    gid: "{{ vault_user_id }}"
    state: present

- name: Add user {{ user }}
  user:
    name: "{{ vault_user }}"
    uid: "{{ vault_user_id }}"
    group: "{{ vault_group }}"
    password: "{{ vault_passwd }}"
    comment: "Vault nologin User"
    home: "/{{ vault_home }}"
    shell: /bin/bash
    skeleton: /etc/skel
    state: present
    create_home: yes
  tags: [ 'vault_user', 'vault_installdir' ]


...
