---
- name: set_fact for localhost
  tags: always
  set_fact:
    env: "{{ ansible_hostname.split('usctvl')[1] }}"
    env0: "{{ ansible_hostname.split('tst')[1] }}"
    local_env: "{{ ansible_hostname.split('usctvl(tst|dev|qa|prd)') }}"
  when: ansible_hostname is search('usctvl(tst|dev|qa|prd)')

- debug:
    msg: "Vault Server : {{ env }} {{env0}} HostName is {{ local_env }}"

- assert:
    that:
      - env is search('tst|dev|qa|prd')

- name: Creating vault user group
  group:
    name: "{{ vault_group }}"
  become: no

- name: Creating vault user
  user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    system: yes
    shell: "/sbin/nologin"
    comment: "vault nologin User"
    createhome: "no"
    state: present

- name: Dowlnoad Vault from HashiCorp
  get_url:
    url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    dest: "/tmp/vault_{{ vault_version }}_linux_amd64.zip"

- name: Extract Vault Archive
  unarchive:
    src: "/tmp/vault_{{ vault_version }}_linux_amd64.zip"
    dest: "/usr/bin"
    copy: no
  register: unarchiveVault
  tags: unarchiveVault

- debug:
    msg: "{{ unarchiveVault }}"

- name: Remove archive
  file:
    path: "/tmp/vault_{{ vault_version }}_linux_amd64.zip"
    state: absent

- name: Create Vault Server Dirs
  file:
    path: "{{ item}}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_user }}"
    mode: 0755
  with_items:
    - /etc/vault
    - /apps/data/vault
    - /var/log/vault/logs

- name: copy Vault Server Configs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
  with_items:
    - { src: 'config.json', dest: '/etc/vault/config.json', mode: '0640' }

- name: service | {{ item }}
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - [ 'vault' ]
  tags: vaultService

- name: Modify profile
  lineinfile:
    path: /root/.bash_profile
    line: export VAULT_ADDR=http://10.13.3.10:8200
    insertbefore: "^export PATH"

- name: Check Vault Status
  shell: vault status -address=http://10.13.3.10:8200 | grep -i initialized
  ignore_errors: true
  args:
    warn: false
  register: vaultStatus

- name: Initialize the vault
  shell: vault operator init -key-shares=5 -key-threshold=3 -format json
  environment:
    VAULT_ADDR: "http://10.13.3.10:8200"
  ignore_errors: true
  args:
    warn: true
  when: "vaultStatus.stdout.split()[1] != 'true'"
  register: vaultInitResult

# - debug:
#     msg: "{{ vaultInitResult }}"


- name: Check Vault Status
  shell: vault status -address=http://10.13.3.10:8200 | grep -i initialized
  ignore_errors: true
  args:
    warn: false
  register: vaultStatus

# - debug:
#     msg: "{{ vaultStatus.stdout.split()[1] }}"

#-------------------------------------------------------------------------------
# Extend ability to use the mlock syscall without running the process as root to
#   Vault executable.
#
- name: Define Vault Capabilities
  capabilities:
    path: /usr/bin/vault
    capability: cap_ipc_lock+ep
    state: present

- name: Parse output of vault init
  set_fact:
    vault_init_parsed: "{{ vaultInitResult.stdout | from_json }}"

- name: Write Vault Values to file
  lineinfile:
    create: yes
    dest: /etc/vault/initfile
    state: present
    # line: "{{ vaultInitResult.stdout }}.json"
    line: "{{ vault_init_parsed | to_json }}"

- name: Unseal Vault
  shell: |
    vault operator unseal {{ item }}
  environment:
    VAULT_ADDR: "http://10.13.3.10:8200"
  with_items: "{{ vault_init_parsed |json_query('unseal_keys_hex[*]')}}"

- name: Vault login
  shell: |
    vault login {{ item }}
  environment:
    VAULT_ADDR: "http://10.13.3.10:8200"
  with_items: "{{ vault_init_parsed |json_query('root_token')}}"
  register: vaultLogin

- debug:
    msg: "{{ vaultLogin.changed }}"

- name: Enable Vault Logging
  shell: vault audit enable file file_path="{{ item }}"
  with_items:
    - /var/log/vault/logs/audit.log
  when: "vaultLogin.changed == 'true'"

...
