---
- hosts: all
  gather_facts: true
  become: true
  become_user: root
  become_method: sudo
  tags: always

  vars:
    vaultUrl: http://10.13.3.10
    vaultUrlPort: 8200
    userPassuser: "{{ login }}"

  tasks:
    - debug:
        msg: "Login is {{ userPassuser }}"

     # curl -s -H "X-Vault-Token: s.TYtaD2Eu3lbIQMcYJ9eFwfEn" --request POST \
     #   --data '{"password": "teamcity-svc", "policies": "default,userpass-policy"}'
     #   http://10.13.3.10:8200/v1/auth/userpass/users/teamcity
    
    - name: Create Vault Admin User
      uri:
        url: "{{ vaultUrl }}:{{ vaultUrlPort }}/v1/auth/userpass/users/{{userPassuser}}"
        method: POST
        headers:
          Content-Type: "application/json"
          X-Vault-Token: 's.TYtaD2Eu3lbIQMcYJ9eFwfEn'
        body: {"password": "vaultadmin-svc", "policies": "admin"}
        body_format: json
        status_code: 204
        force_basic_auth: yes
        return_content: yes
      register: createVaultAdmin


    - name: Get VaultAdmin  User Token Password
      uri:
        url: "{{ vaultUrl }}:{{ vaultUrlPort }}/v1/auth/userpass/login/{{ userPassuser }}"
        #url: "{{ vaultUrl }}:{{ vaultUrlPort }}/v1/auth/userpass/login/admin"
        method: POST
        body: {"password": "vaultadmin-svc"}
        body_format: json
        status_code: 200
        force_basic_auth: yes
        return_content: yes
      register: vaultAdminAuthToken

    #- name: Get Vault Admin Token
    #  uri:
    #    method: POST
    #    body: {"password": "vaultadmin-svc" }
    #    status_code: 200
    #    force_basic_auth: yes
    #    return_content: yes
    #  register: vaultAdminToken
  
    - debug:
        msg: "vaultAdminAuthToken {{ vaultAdminAuthToken.json.auth.client_token }}"


