---
# Restart etcd server
#   - etcd

- name: service etcd restart
  tags: etcd
  service:
    name: etcd
    state: restarted

- name: service firewalld restart
  tags: firewalld
  service:
    name: firewalld
    state: restarted

- name: service named restart
  service:
    name: named
    state: restarted
